package tox

/*
#include <tox/tox.h>
#include <tox/toxav.h>
*/
import "C"

const (
	PUBLIC_KEY_SIZE           = int(C.TOX_PUBLIC_KEY_SIZE)
	SECRET_KEY_SIZE           = int(C.TOX_SECRET_KEY_SIZE)
	ADDRESS_SIZE              = int(C.TOX_ADDRESS_SIZE)
	MAX_NAME_LENGTH           = int(C.TOX_MAX_NAME_LENGTH)
	MAX_STATUS_MESSAGE_LENGTH = int(C.TOX_MAX_STATUS_MESSAGE_LENGTH)
	MAX_FRIEND_REQUEST_LENGTH = int(C.TOX_MAX_FRIEND_REQUEST_LENGTH)
	MAX_MESSAGE_LENGTH        = int(C.TOX_MAX_MESSAGE_LENGTH)
	MAX_CUSTOM_PACKET_SIZE    = int(C.TOX_MAX_CUSTOM_PACKET_SIZE)
	HASH_LENGTH               = int(C.TOX_HASH_LENGTH)
	FILE_ID_LENGTH            = int(C.TOX_FILE_ID_LENGTH)
	MAX_FILENAME_LENGTH       = int(C.TOX_MAX_FILENAME_LENGTH)
)
