//go:generate stringer -type=TOXAV_ERR_NEW,TOXAV_ERR_CALL,TOXAV_ERR_ANSWER,TOXAV_FRIEND_CALL_STATE,TOXAV_CALL_CONTROL,TOXAV_ERR_CALL_CONTROL,TOXAV_ERR_BIT_RATE_SET,TOXAV_ERR_SEND_FRAME
package toxenums

import "fmt"

type TOXAV_ERR_NEW int

const (
	TOXAV_ERR_NEW_OK TOXAV_ERR_NEW = iota
	TOXAV_ERR_NEW_NULL
	TOXAV_ERR_NEW_MALLOC
	TOXAV_ERR_NEW_MULTIPLE
)

type TOXAV_ERR_CALL int

const (
	TOXAV_ERR_CALL_OK TOXAV_ERR_CALL = iota
	TOXAV_ERR_CALL_MALLOC
	TOXAV_ERR_CALL_SYNC
	TOXAV_ERR_CALL_FRIEND_NOT_FOUND
	TOXAV_ERR_CALL_FRIEND_NOT_CONNECTED
	TOXAV_ERR_CALL_FRIEND_ALREADY_IN_CALL
	TOXAV_ERR_CALL_INVALID_BIT_RATE
)

type TOXAV_ERR_ANSWER int

const (
	TOXAV_ERR_ANSWER_OK TOXAV_ERR_ANSWER = iota
	TOXAV_ERR_ANSWER_SYNC
	TOXAV_ERR_ANSWER_CODEC_INITIALIZATION
	TOXAV_ERR_ANSWER_FRIEND_NOT_FOUND
	TOXAV_ERR_ANSWER_FRIEND_NOT_CALLING
	TOXAV_ERR_ANSWER_INVALID_BIT_RATE
)

type TOXAV_FRIEND_CALL_STATE int

const (
	TOXAV_FRIEND_CALL_STATE_NONE        TOXAV_FRIEND_CALL_STATE = 0
	TOXAV_FRIEND_CALL_STATE_ERROR       TOXAV_FRIEND_CALL_STATE = 1
	TOXAV_FRIEND_CALL_STATE_FINISHED    TOXAV_FRIEND_CALL_STATE = 2
	TOXAV_FRIEND_CALL_STATE_SENDING_A   TOXAV_FRIEND_CALL_STATE = 4
	TOXAV_FRIEND_CALL_STATE_SENDING_V   TOXAV_FRIEND_CALL_STATE = 8
	TOXAV_FRIEND_CALL_STATE_ACCEPTING_A TOXAV_FRIEND_CALL_STATE = 16
	TOXAV_FRIEND_CALL_STATE_ACCEPTING_V TOXAV_FRIEND_CALL_STATE = 32
)

type TOXAV_CALL_CONTROL int

const (
	TOXAV_CALL_CONTROL_RESUME TOXAV_CALL_CONTROL = iota
	TOXAV_CALL_CONTROL_PAUSE
	TOXAV_CALL_CONTROL_CANCEL
	TOXAV_CALL_CONTROL_MUTE_AUDIO
	TOXAV_CALL_CONTROL_UNMUTE_AUDIO
	TOXAV_CALL_CONTROL_HIDE_VIDEO
	TOXAV_CALL_CONTROL_SHOW_VIDEO
)

type TOXAV_ERR_CALL_CONTROL int

const (
	TOXAV_ERR_CALL_CONTROL_OK TOXAV_ERR_CALL_CONTROL = iota
	TOXAV_ERR_CALL_CONTROL_SYNC
	TOXAV_ERR_CALL_CONTROL_FRIEND_NOT_FOUND
	TOXAV_ERR_CALL_CONTROL_FRIEND_NOT_IN_CALL
	TOXAV_ERR_CALL_CONTROL_INVALID_TRANSITION
)

type TOXAV_ERR_BIT_RATE_SET int

const (
	TOXAV_ERR_BIT_RATE_SET_OK TOXAV_ERR_BIT_RATE_SET = iota
	TOXAV_ERR_BIT_RATE_SET_SYNC
	TOXAV_ERR_BIT_RATE_SET_INVALID_BIT_RATE
	TOXAV_ERR_BIT_RATE_SET_FRIEND_NOT_FOUND
	TOXAV_ERR_BIT_RATE_SET_FRIEND_NOT_IN_CALL
)

type TOXAV_ERR_SEND_FRAME int

const (
	TOXAV_ERR_SEND_FRAME_OK TOXAV_ERR_SEND_FRAME = iota
	TOXAV_ERR_SEND_FRAME_NULL
	TOXAV_ERR_SEND_FRAME_FRIEND_NOT_FOUND
	TOXAV_ERR_SEND_FRAME_FRIEND_NOT_IN_CALL
	TOXAV_ERR_SEND_FRAME_SYNC
	TOXAV_ERR_SEND_FRAME_INVALID
	TOXAV_ERR_SEND_FRAME_PAYLOAD_TYPE_DISABLED
	TOXAV_ERR_SEND_FRAME_RTP_FAILED
)

func (e TOXAV_ERR_NEW) Error() string {
	return fmt.Sprintf("tox err: %s (%d)", (interface{})(e).(fmt.Stringer).String(), e)
}
func (e TOXAV_ERR_CALL) Error() string {
	return fmt.Sprintf("tox err: %s (%d)", (interface{})(e).(fmt.Stringer).String(), e)
}
func (e TOXAV_ERR_ANSWER) Error() string {
	return fmt.Sprintf("tox err: %s (%d)", (interface{})(e).(fmt.Stringer).String(), e)
}
func (e TOXAV_ERR_CALL_CONTROL) Error() string {
	return fmt.Sprintf("tox err: %s (%d)", (interface{})(e).(fmt.Stringer).String(), e)
}
func (e TOXAV_ERR_BIT_RATE_SET) Error() string {
	return fmt.Sprintf("tox err: %s (%d)", (interface{})(e).(fmt.Stringer).String(), e)
}
func (e TOXAV_ERR_SEND_FRAME) Error() string {
	return fmt.Sprintf("tox err: %s (%d)", (interface{})(e).(fmt.Stringer).String(), e)
}
